### ISSUE TITLE
Separate targets for email notifications

### ISSUE THREAD

**Issue by 8vius** [simukappu/activity_notification#47]
In my app users can select if they want to receive notifications via email, in system or both. Is there a way to separate targets so if a user has selected email only he only gets the email?

**Comment by simukappu** [comment]
Hi @8vius 

No, you cannot send notification email only. Notification email has a link to notifiable page and this link is managed by Notifiable model in notification data records. That's why you have to generate notification records if you want to send notification email.
On the other hand, You can generate notification record only, not send email. In addition, you can hide notification records in your custom view. In this case, the users need not be aware of existing notification records.
Do you have any problem about this for your use case?

Thanks!

**Comment by 8vius** [comment]
It is a problem, since it forces me to not use the convenient email options already included in the gem. Would be nice if separate targets could be specified.

**Comment by simukappu** [comment]
The problem is that creating the link to notifiable page needs DB record of notification. Do you have any suggestion about this?
As your option, you can generate both of email and record for topic A (notification key) to email subscriber and generate record only for  topic B to notification subscriber. And you will manage notification view to show topic B only.
