### ISSUE TITLE
Emails not being sent

### ISSUE THREAD

**Issue by jakehockey10** [simukappu/activity_notification#73]
Hello,

I followed the documentation in the README, and I can't seem to get emails to send.  I'm getting the notifications I expect in the notifications index page, but I'm not getting emails for subscribed users.  I've enabled emails with `config.email_enabled = true`.  In `production.rb`, my email is configured as such

``` ruby

  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
      user_name: ENV['SENDGRID_USERNAME'],
      password: ENV['SENDGRID_PASSWORD'],
      domain: 'heroku.com',
      address: 'smtp.sendgrid.net',
      port: 587,
      authentication: :plain,
      enable_starttls_auto: true
  }

```

My `user.rb` model is configured as such: `acts_as_target email: :email, email_allowed: :activated_at`.

My notifiable model is configured as such: 
``` ruby
acts_as_notifiable :users,
                   targets: ->(_model, _key) {User.all.to_a},
                   tracked: true
```

**Comment by johncadengo** [comment]
@jakehockey10 did you ever get this to work?

**Comment by jakehockey10** [comment]
Unfortunately not yet.  Still hoping to figure it out sometime...don't get to work on this project very often!

**Comment by jefrice** [comment]
I had to set the env variables SENDGRID_USERNAME & SENDGRID_PASSWORD before it would work. For dev, I did this in my terminal. For Heroku, I did this on the settings environment variables. Then it worked.

**Comment by simukappu** [comment]
Hi @jakehockey10,
It seems to be an issue about action_mailer configuration. Did you ever get this to work?
Do we have to keep this issue opened?

**Comment by jakehockey10** [comment]
I haven't got this to work. I have my environment variables set. I'm not sure what keeping this open will do so you can close it if you like

**Comment by simukappu** [comment]
Thanks - @jakehockey10. Can you send email to user from other channels with action_mailer such as Devise?
Does anybody have a same problem?

**Comment by brunitob** [comment]
Any progress on this?

**Comment by SilverStrangeTech** [comment]
@jakehockey10 
I recently set up email notifications on my own project. I have a couple thoughts if you are still having problems.

Add the email_allowed key to your acts_as_notifiable (as shown in the readme).
```ruby
acts_as_notifiable
       :users,
       targets: ->(_model, _key) {User.all.to_a},
       tracked: true,
       # Allow notification email
       email_allowed: true
```

The send_later option defaults to true. This makes debugging difficult because the emails are sent by your job queue and they don't show up in your server logs. If you change send_later to false, then rails will immediately attempt to send the email notification and the output will be logged normally. (I'm not sure if this applies to Heroku, I've never really used Heroku and I'm not sure how their rails logs work).
```ruby
acts_as_notifiable :users,
                   targets: ->(_model, _key) {User.all.to_a},
                   tracked: { send_later: false },
                   # Allow notification email
                   email_allowed: true
```
If the email notification sends normally after this, that probably indicates a problem with your job queue. (For example, you might not have provided workers for your queue).

My problem turned out to be that I didn't have the appropriate template in views/activity_notifications/mailer/users/<target>/<key>.html.erb. I was able to see the error in my rails log once I set 'send_later: false'.

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
