### ISSUE TITLE
Design decision around requiring an optional target subscription to require a notification subscription?

### ISSUE THREAD

**Issue by markedmondson** [simukappu/activity_notification#90]
Looking at this code:

https://github.com/simukappu/activity_notification/blob/11d113a73480f43bcbb159063f5c5f1d5c95b3c2/lib/activity_notification/models/concerns/subscriber.rb#L160-L163

(specifically `_subscribes_to_notification?(key, subscribe_as_default) &&`)

It requires a key to be subscribed to for optional target subscription to also work. The same is not true of email subscriptions. What's the thought process behind this? 

Our use case is allowing the user to disable in-app notifications but still be subscribed to push notifications. We're filtering out the unsubscribed in-app notifications using `:filter_by_key` in the notifications controller.

**Comment by simukappu** [comment]
Hi @markedmondson,

Subscription to notification (this means `subscribing` column of *Subscription* records) represents if *activity_notification* gem will create *Notification* records for the target or not. This can be specified for each notification key.
All notification functions in *activity_notification* are based on saved notification records. Therefore, you **cannot** create notification view, prepare notification email text and generate link to notifiable page without notification records.
That's why you need to subscribe to notification and save *Notification* records even if you will not subscribe to email notification or optional targets.
Does this make sense for you?

**Comment by simukappu** [comment]
Yes, appreciate it. But we have to keep API compatibility, so please check to pass the tests. Thanks!

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
